#!/usr/bin/env bash
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
selector="$(cd "$script_dir/../../.." && pwd)/scripts/ci/select_android_test_tasks.sh"
tmp_dir="$(mktemp -d)"; trap 'rm -rf "$tmp_dir"' EXIT
assert_contains() { grep -Fx -- "$1" "$2" >/dev/null || { echo "missing $1" >&2; exit 1; }; }
assert_empty() { [[ ! -s "$1" ]] || { echo "expected empty output" >&2; exit 1; }; }
printf 'impact\nmodules/core/src/main.kt\n' > "$tmp_dir/source"
bash "$selector" /dev/null "$tmp_dir/source" > "$tmp_dir/out"
assert_contains ':app:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:appconfig:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:record:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:settings:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:ui:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:common:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:forward:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:sender:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:verification:testGithubDebugUnitTest' "$tmp_dir/out"
printf 'impact\nmobile/ui/src/main.kt\n' > "$tmp_dir/mobile"
bash "$selector" /dev/null "$tmp_dir/mobile" > "$tmp_dir/out"
assert_contains ':mobile:feature:overview:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:forward:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':mobile:feature:sender:testGithubDebugUnitTest' "$tmp_dir/out"
printf 'impact\nfrontend/webui/src/App.tsx\n' > "$tmp_dir/web"
bash "$selector" /dev/null "$tmp_dir/web" > "$tmp_dir/out"; assert_empty "$tmp_dir/out"
printf 'full\n' > "$tmp_dir/full"
bash "$selector" /dev/null "$tmp_dir/full" > "$tmp_dir/out"; assert_contains 'verifyStructureBoundaries' "$tmp_dir/out"; assert_contains ':mobile:ui:testGithubDebugUnitTest' "$tmp_dir/out"; assert_contains ':magisk-ui-kit:testAndroidHostTest' "$tmp_dir/out"
assert_contains ':desktop:compileKotlinJvm' "$tmp_dir/out"
assert_contains ':desktop:core:jvmTest' "$tmp_dir/out"
assert_contains ':desktop:data:jvmTest' "$tmp_dir/out"
assert_contains ':policy:jvmTest' "$tmp_dir/out"
assert_contains ':relay:contract:jvmTest' "$tmp_dir/out"
assert_contains ':relay:net:jvmTest' "$tmp_dir/out"
assert_contains ':relay:sender:api:jvmTest' "$tmp_dir/out"
printf 'impact\nmagisk-ui-kit/src/main.kt\n' > "$tmp_dir/kit"
bash "$selector" /dev/null "$tmp_dir/kit" > "$tmp_dir/out"
assert_contains ':magisk-ui-kit:testAndroidHostTest' "$tmp_dir/out"
assert_contains ':magisk-ui-kit:billing:testDebugUnitTest' "$tmp_dir/out"
printf 'impact\ndesktop/src/jvmMain/kotlin/Main.kt\n' > "$tmp_dir/desktop_src"
bash "$selector" /dev/null "$tmp_dir/desktop_src" > "$tmp_dir/out"
assert_contains ':desktop:compileKotlinJvm' "$tmp_dir/out"
assert_contains ':desktop:jvmTest' "$tmp_dir/out"
assert_contains ':desktop:core:jvmTest' "$tmp_dir/out"
assert_contains ':desktop:data:jvmTest' "$tmp_dir/out"
assert_contains 'verifyStructureBoundaries' "$tmp_dir/out"
printf 'impact\nmodules/desktop/data/src/jvmMain/kotlin/Store.kt\n' > "$tmp_dir/desktop_moved"
bash "$selector" /dev/null "$tmp_dir/desktop_moved" > "$tmp_dir/out"
assert_contains ':desktop:jvmTest' "$tmp_dir/out"
assert_contains ':desktop:data:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/sender/api/src/commonMain/kotlin/SenderSettingDraft.kt\n' > "$tmp_dir/kmp"
bash "$selector" /dev/null "$tmp_dir/kmp" > "$tmp_dir/out"
assert_contains ':app:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':policy:jvmTest' "$tmp_dir/out"
assert_contains ':relay:contract:jvmTest' "$tmp_dir/out"
assert_contains ':relay:net:jvmTest' "$tmp_dir/out"
assert_contains ':relay:sender:api:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/policy/src/commonMain/kotlin/WorkMode.kt\n' > "$tmp_dir/policy"
bash "$selector" /dev/null "$tmp_dir/policy" > "$tmp_dir/out"
assert_contains ':app:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':policy:jvmTest' "$tmp_dir/out"
assert_contains ':relay:sender:api:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/engine/src/commonMain/kotlin/NotifyRoutingResolver.kt\n' > "$tmp_dir/engine"
bash "$selector" /dev/null "$tmp_dir/engine" > "$tmp_dir/out"
assert_contains ':app:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':relay:engine:jvmTest' "$tmp_dir/out"
assert_contains ':relay:net:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/engine/src/jvmTest/kotlin/ForwardFilterEngineTest.kt\n' > "$tmp_dir/engine_test"
bash "$selector" /dev/null "$tmp_dir/engine_test" > "$tmp_dir/out"
assert_contains ':relay:engine:jvmTest' "$tmp_dir/out"
assert_contains ':policy:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/engine/api/src/androidMain/kotlin/Sender.kt\n' > "$tmp_dir/engine_api"
bash "$selector" /dev/null "$tmp_dir/engine_api" > "$tmp_dir/out"
assert_contains ':relay:engine:jvmTest' "$tmp_dir/out"
assert_contains ':relay:sender:api:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/matrix-e2ee/src/commonMain/kotlin/MatrixE2eeSendPolicy.kt\n' > "$tmp_dir/matrix"
bash "$selector" /dev/null "$tmp_dir/matrix" > "$tmp_dir/out"
assert_contains ':app:testGithubDebugUnitTest' "$tmp_dir/out"
assert_contains ':relay:matrix-e2ee:jvmTest' "$tmp_dir/out"
assert_contains ':relay:engine:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/matrix-e2ee/src/androidMain/kotlin/MatrixE2eeRuntime.kt\n' > "$tmp_dir/matrix_android"
bash "$selector" /dev/null "$tmp_dir/matrix_android" > "$tmp_dir/out"
assert_contains ':relay:matrix-e2ee:jvmTest' "$tmp_dir/out"
assert_contains ':relay:net:jvmTest' "$tmp_dir/out"
printf 'impact\nmodules/relay/matrix-e2ee/src/jvmTest/kotlin/RoomCryptoStateTest.kt\n' > "$tmp_dir/matrix_test"
bash "$selector" /dev/null "$tmp_dir/matrix_test" > "$tmp_dir/out"
assert_contains ':relay:matrix-e2ee:jvmTest' "$tmp_dir/out"
assert_contains ':policy:jvmTest' "$tmp_dir/out"
echo 'xinyi selector tests passed'
