// Generated from Kotlin config models by
// scripts/codegen/generate_config_root_contract.py.
// Do not edit this file by hand.

import type { SenderActiveSchedule } from '../senderActiveSchedule'

export interface RemoteConfigRoot extends Record<string, unknown> {
  general: GeneralSettingsSnapshot
  verification: VerificationSettingsSnapshot
  relay: RelaySettingsSnapshot
  diagnostics: DiagnosticsSettingsSnapshot
  advanced: AdvancedSettingsSnapshot
  specialAlerts: SpecialAlertSettingsSnapshot
  messageTypeGates: MessageTypeGateSnapshot
  forwardTypeGates: ForwardTypeGateSnapshot
  records: RecordSettingsSnapshot
  smsBlacklist: SmsBlacklistSettingsSnapshot
  simRemarks: SimRemarkSettingsSnapshot
  forwardCommon: ForwardCommonConfig
  appNotifyTemplate: string
  callNotifyTemplate: string
  overview: SnapshotOverviewSettings
  senders: Array<SnapshotSender>
  rules: Array<SnapshotRule>
  smsCodeRules: Array<SnapshotSmsCodeRule>
  deviceAppInfos?: Record<string, Array<SnapshotAppInfo>> | null
  notifyRoutes: Array<SnapshotNotifyRouteRule>
  forwardFilters: Array<SnapshotForwardFilterRule>
}

export interface SnapshotForwardFilterRule {
  id: number
  msgType: string
  scopeType: string
  scopeKey: string
  senderId: number
  policy: string
  matchMode: string
  pattern: string
  enabled: number
  updateTime: number
}

export interface SnapshotNotifyRouteRule {
  id: number
  scope: number
  packageName: string
  senderId: number
  updateTime: number
}

export interface SnapshotAppInfo {
  packageName: string
  label?: string | null
  blocked: boolean
  forwarding: boolean
  forwardingConfigured: boolean
  notifyTemplate: string
}

export interface SnapshotSmsCodeRule {
  company?: string | null
  codeKeyword: string
  codeRegex: string
  id: number
}

export interface SnapshotRule {
  id: number
  type: string
  filed: string
  check: string
  value: string
  senderId: number
  smsTemplate?: string
  regexReplace?: string
  simSlot?: string
  status: number
  time?: number
  senderList?: Array<SnapshotSender>
  senderLogic?: string
  silentPeriodStart?: number
  silentPeriodEnd?: number
  silentDayOfWeek?: string
  title: string
}

export interface SnapshotSender {
  id: number
  type: number
  name: string
  jsonSetting: string
  status: number
  time?: number
  receiveCode: number
  receiveNonCode: number
  receiveAppNotify: number
  receiveCallNotify: number
  activeSchedule?: SenderActiveSchedule
  priority?: number
  customTemplate?: string
}

export interface SnapshotOverviewSettings {
  cardOrder: string
  enabledCardIds: string
  chartType: string
  chartWindow: string
}

export interface ForwardCommonConfig {
  deviceName?: string
  messageTemplate?: string
  includeTime?: boolean
  includeSender?: boolean
  includeDeviceName?: boolean
  dispatchStrategy?: number
  silentPeriod?: ForwardSilentPeriodConfig
}

export interface ForwardSilentPeriodConfig {
  enabled?: boolean
  start?: string
  end?: string
  weekdays?: Array<number>
}

export interface SimRemarkSettingsSnapshot {
  simSlot1Remark: string
  simSlot2Remark: string
}

export interface SmsBlacklistSettingsSnapshot {
  enabled: boolean
  deleteBlockedSms: boolean
  blockIncomingSms: boolean
  numbers: string
  prefixes: string
  regexRules: string
  contentRules: string
}

export interface RecordSettingsSnapshot {
  previousRecordEnabled: boolean
  codeRecordEnabled: boolean
  plainSmsRecordEnabled: boolean
  appNotifyRecordEnabled: boolean
  callNotifyRecordEnabled: boolean
  codeHistoryLimit: string
  plainSmsHistoryLimit: string
  appNotifyHistoryLimit: string
  callNotifyHistoryLimit: string
  smsBlacklistHitRecordEnabled?: boolean
  smsBlacklistHitHistoryLimit?: string
}

export interface ForwardTypeGateSnapshot {
  smsCodeEnabled: boolean
  smsPlainEnabled: boolean
  appNotifyEnabled: boolean
  callNotifyEnabled: boolean
  callNotifyFinalEnabled: boolean
}

export interface MessageTypeGateSnapshot {
  smsCodeEnabled: boolean
  smsPlainEnabled: boolean
  appNotifyEnabled: boolean
  callNotifyEnabled: boolean
}

export interface SpecialAlertSettingsSnapshot {
  lowBatteryReminderEnabled: boolean
  lowBatteryThreshold: number
  lowBatteryChannelId: string
  fullBatteryReminderEnabled: boolean
  fullBatteryChannelId: string
  chargingChangeReminderEnabled: boolean
  chargingChangeChannelId: string
  callAlertLocalEnabled: boolean
  callAlertChannelId: string
  smsKeywordEnabled: boolean
  smsKeywordKeywords: string
  smsKeywordNotificationEnabled: boolean
  smsKeywordSoundEnabled: boolean
  smsKeywordVibrateEnabled: boolean
  appKeywordEnabled: boolean
  appKeywordKeywords: string
  appKeywordNotificationEnabled: boolean
  appKeywordSoundEnabled: boolean
  appKeywordVibrateEnabled: boolean
}

export interface AdvancedSettingsSnapshot {
  enableSmsBlacklist: boolean
}

export interface DiagnosticsSettingsSnapshot {
  rootDbCatchupEnabled: boolean
  rootDbCatchupIntervalMin: string
  rootDbCatchupWriteback: boolean
  forceStopRecoveryEnabled: boolean
  forceStopRecoveryRelaunchOnceEnabled: boolean
  verboseLogMode: boolean
  sensitiveDebugLogMode: boolean
  runtimeLogRetentionDays: number
  autoUpdateOnStart: boolean
  autoUpdateWifiOnly: boolean
  analyticsEnabled: boolean
  keepAliveOomAdj: boolean
  keepAliveAntiKill: boolean
  keepAliveStandbyBypass: boolean
  keepAliveDozeBypass: boolean
  keepAliveAccessibilityHeartbeat: boolean
  keepAliveDedicatedService: boolean
}

export interface RelaySettingsSnapshot {
  relayFeaturesEnabled: boolean
  smsForwardDedupWindowSec: number
}

export interface VerificationSettingsSnapshot {
  verificationFeaturesEnabled: boolean
  copyToClipboard: boolean
  showToast: boolean
  showCodeNotification: boolean
  autoCancelNotification: boolean
  notificationRetentionTime: string
  autoInputEnabled: boolean
  autoEnterEnabled: boolean
  autoInputDelay: string
  autoInputInterval: string
  relayKeywords: string
  blockSmsEnabled: boolean
}

export interface GeneralSettingsSnapshot {
  moduleEnabled: boolean
  accordionMode: boolean
}
