// Generated from frontend/shared/contracts/openapi.json by
// scripts/codegen/generate_console_contract_from_openapi.py.
// Do not edit this file by hand.

export interface AgentConfigCommandsAckRequest {
  appliedRevision: number
  commandId: number
  failureReason?: string
  mirrorContent: JsonObject
  status: string
}

export interface AgentConfigCommandsPullRequest {
  localRevision: number
}

export interface AgentConfigCommandsPullResponse {
  deviceId: number
  mirrorContent?: JsonObject | null
  pendingCommands: Array<DeviceConfigCommandItem>
  revision: number
  updatedAt: string
}

export interface AgentConfigMirrorRequest {
  localRevision: number
  mirrorContent: JsonObject
  summary?: string
}

export interface AgentRegisterRequest {
  appVersion: string
  bindCode: string
  deviceModel: string
  deviceName: string
  platform: string
}

export interface AgentRegisterResponse {
  deviceId: number
  deviceToken: string
  userId: number
}

export interface BindCodeResponse {
  code: string
  expiresAt: string
}

export interface BootstrapAdminRequest {
  password: string
  username: string
}

export interface BootstrapAdminResponse {
  ok: boolean
  userId: number
  username: string
}

export interface ChangePasswordRequest {
  currentPassword: string
  newPassword: string
}

export interface DesktopExchangeRequest {
  code: string
}

export interface DesktopLoginPageRequest {
  client_name: string
  password: string
  redirect_uri: string
  state: string
  username: string
}

export interface DesktopLogoutRequest {
  refreshToken: string
}

export interface DesktopRefreshRequest {
  refreshToken: string
}

export interface DesktopSessionResponse {
  accessToken: string
  authenticated: boolean
  expiresAt: string
  refreshExpiresAt: string
  refreshToken: string
  username: string
}

export interface DeviceConfigAuditLogItem {
  actorId: number
  actorType: string
  commandId?: number | null
  createdAt: string
  deviceId: number
  eventType: string
  id: number
  revision: number
  summary: string
}

export interface DeviceConfigAuditLogsResponse {
  limit: number
  logs: Array<DeviceConfigAuditLogItem>
  offset: number
}

export interface DeviceConfigCommandItem {
  actorId: number
  actorType: string
  appliedAt?: string | null
  baseRevision: number
  createdAt: string
  failureReason?: string | null
  id: number
  mutation: JsonObject
  status: string
  summary: string
  targetRevision: number
  updatedAt: string
}

export interface DeviceConfigCommandRequest {
  baseRevision: number
  mutation: JsonObject
  summary: string
}

export interface DeviceConfigStateResponse {
  deviceId: number
  mirrorContent?: JsonObject | null
  pendingCommands: Array<DeviceConfigCommandItem>
  revision: number
  updatedAt: string
}

export interface DeviceItem {
  appVersion: string
  capabilities: JsonObject
  createdAt: string
  deviceModel: string
  deviceName: string
  displayName: string
  enabled: boolean
  id: number
  lastSeenAt?: string | null
  localAddresses: JsonObject
  platform: string
  revokedAt?: string | null
  updatedAt: string
  userId: number
}

export interface DevicesResponse {
  devices: Array<DeviceItem>
}

export interface ErrorResponse {
  error: string
}

export interface HealthResponse {
  ok: boolean
  service: string
}

export interface HeartbeatRequest {
  appVersion: string
  capabilities: Record<string, boolean>
  localAddresses: Array<string>
}

export type JsonObject = Record<string, unknown>

export interface LoginRequest {
  password: string
  username: string
}

export interface LoginResponse {
  authenticated: boolean
  csrfToken: string
  languageTag?: string | null
  username: string
}

export interface MeResponse {
  authenticated?: boolean
  csrfToken?: string | null
  languageTag?: string | null
  username?: string | null
}

export interface PatchDeviceRequest {
  displayName?: string | null
  enabled?: boolean | null
}

export interface RealtimeEvent {
  data?: JsonObject | null
  time: string
  type: "device.registered" | "device.updated" | "device.revoked" | "device.heartbeat" | "device.config.updated" | "device.config.command.updated" | "records.ingested"
}

export interface RecordsResponse {
  limit: number
  offset: number
  records: Array<RelayRecord>
}

export interface RelayRecord {
  body: string
  callType: number
  deviceId: number
  eventId?: string | null
  id: number
  metadata: JsonObject
  msgType: number
  occurredAt: string
  packageName: string
  recordType: string
  sender: string
  smsCode: string
  uploadedAt: string
}

export interface RelayRecordWire {
  body: string
  callType: number
  eventId: string
  metadata: JsonObject
  msgType: number
  occurredAt: string
  packageName: string
  recordType: string
  sender: string
  smsCode: string
}

export interface RelayRecordsBatchRequest {
  records: Array<RelayRecordWire>
  replaceExisting?: boolean
}

export interface RelayRecordsBatchResponse {
  deleted?: number
  inserted: number
  updated?: number
}

export interface SimpleOKResponse {
  ok: boolean
}

export interface SystemInfoResponse {
  appEnv: string
  databaseReady: boolean
  localBaseUrl: string
  publicBaseUrl: string
  service: string
  time: string
  userCount: number
}
