package io.github.magisk317.relay.contract.constant

object RelayPrefConst {

    // General
    const val KEY_ENABLE = "pref_enable"
    const val KEY_HIDE_LAUNCHER_ICON = "pref_hide_launcher_icon"
    const val KEY_SHOW_LAUNCHER_ICON = "pref_show_launcher_icon"
    const val KEY_CHOOSE_THEME = "pref_choose_theme"
    const val KEY_UI_KIT_STYLE = "pref_ui_kit_style"
    const val KEY_LANGUAGE = "pref_language"
    const val KEY_COMPOSE_SETTINGS = "pref_compose_settings"
    const val KEY_SETTINGS_ACCORDION_MODE = "pref_settings_accordion_mode"
    const val KEY_HAZE_BLUR_RADIUS = "pref_haze_blur_radius"
    const val HAZE_BLUR_RADIUS_DEFAULT = 25
    const val KEY_HAZE_TINT_ALPHA = "pref_haze_tint_alpha"
    const val HAZE_TINT_ALPHA_DEFAULT = 0.2f

    // SMS Code
    const val KEY_SHOW_TOAST = "pref_show_toast"
    const val KEY_COPY_TO_CLIPBOARD = "pref_copy_to_clipboard"
    const val KEY_ENABLE_AUTO_INPUT_CODE = "pref_enable_auto_input_code"
    const val KEY_ENABLE_AUTO_ENTER_CODE = "pref_enable_auto_enter_code"
    const val KEY_AUTO_INPUT_CODE_DELAY = "pref_auto_input_code_delay"
    const val KEY_AUTO_INPUT_CODE_DELAY_DEFAULT = "0"
    const val KEY_AUTO_INPUT_CODE_INTERVAL = "pref_auto_input_code_interval"
    const val KEY_AUTO_INPUT_CODE_INTERVAL_DEFAULT = "80"
    const val KEY_APP_BLOCK_ENTRY = "pref_app_block_entry"
    const val KEY_BLOCK_SMS = "pref_block_sms"
    const val KEY_DEDUPLICATE_SMS = "pref_deduplicate_sms"
    const val KEY_ENABLE_SMS_BLACKLIST = "pref_enable_sms_blacklist"
    const val KEY_SMS_BLACKLIST_NUMBERS = "pref_sms_blacklist_numbers"
    const val KEY_SMS_BLACKLIST_PREFIXES = "pref_sms_blacklist_prefixes"
    const val KEY_SMS_BLACKLIST_REGEX = "pref_sms_blacklist_regex"
    const val KEY_SMS_BLACKLIST_CONTENT = "pref_sms_blacklist_content"
    const val KEY_SMS_BLACKLIST_ACTION_DELETE = "pref_sms_blacklist_action_delete"
    const val KEY_SMS_BLACKLIST_ACTION_BLOCK = "pref_sms_blacklist_action_block"

    // Code Notification
    const val KEY_SHOW_CODE_NOTIFICATION = "pref_show_code_notification"
    const val KEY_CODE_NOTIFICATION_OWNER = "pref_code_notification_owner"
    const val KEY_AUTO_CANCEL_CODE_NOTIFICATION = "pref_auto_cancel_code_notification"
    const val KEY_NOTIFICATION_RETENTION_TIME = "pref_notification_retention_time"
    const val NOTIFICATION_RETENTION_TIME_DEFAULT = "5"
    const val KEY_CODE_NOTIFICATION_RETENTION_TIME = "pref_code_notification_retention_time"
    const val KEY_CODE_NOTIFICATION_RETENTION_TIME_DEFAULT = NOTIFICATION_RETENTION_TIME_DEFAULT
    const val KEY_APP_NOTIFY_CODE_RETENTION_TIME = "pref_app_notify_code_retention_time"
    const val KEY_APP_NOTIFY_CODE_RETENTION_TIME_DEFAULT = NOTIFICATION_RETENTION_TIME_DEFAULT
    const val KEY_CALL_NOTIFY_CODE_RETENTION_TIME = "pref_call_notify_code_retention_time"
    const val KEY_CALL_NOTIFY_CODE_RETENTION_TIME_DEFAULT = NOTIFICATION_RETENTION_TIME_DEFAULT

    // Code Record
    const val KEY_ENABLE_CODE_RECORDS = "pref_enable_code_records"
    const val MAX_SMS_RECORDS_COUNT_DEFAULT = 20
    const val KEY_ENTRY_CODE_RECORDS = "pref_entry_code_records"
    const val KEY_HISTORY_LIMIT = "pref_history_limit"
    const val KEY_ENABLE_CODE_RECORDS_CODE = "pref_enable_code_records_code"
    const val KEY_ENABLE_CODE_RECORDS_PLAIN_SMS = "pref_enable_code_records_plain_sms"
    const val KEY_ENABLE_CODE_RECORDS_APP_NOTIFY = "pref_enable_code_records_app_notify"
    const val KEY_ENABLE_CODE_RECORDS_CALL_NOTIFY = "pref_enable_code_records_call_notify"
    const val KEY_HISTORY_LIMIT_CODE = "pref_history_limit_code"
    const val KEY_HISTORY_LIMIT_PLAIN_SMS = "pref_history_limit_plain_sms"
    const val KEY_HISTORY_LIMIT_APP_NOTIFY = "pref_history_limit_app_notify"
    const val KEY_HISTORY_LIMIT_CALL_NOTIFY = "pref_history_limit_call_notify"
    const val KEY_ROOT_DB_CATCHUP_ENABLE = "pref_root_db_catchup_enable"
    const val KEY_ROOT_DB_CATCHUP_INTERVAL_MIN = "pref_root_db_catchup_interval_min"
    const val KEY_ROOT_DB_CATCHUP_WRITEBACK = "pref_root_db_catchup_writeback"
    const val KEY_INTERNAL_ROOT_DB_LAST_SMS_ID = "internal_root_db_last_sms_id"
    const val KEY_INTERNAL_ROOT_DB_LAST_CALL_ID = "internal_root_db_last_call_id"
    const val KEY_INTERNAL_ROOT_DB_BASELINE_INITED = "internal_root_db_baseline_inited"

    // Code Rules
    const val KEY_SMSCODE_KEYWORDS = "pref_smscode_keywords"
    const val KEY_SMSCODE_KEYWORDS_EXCLUDE = "pref_smscode_keywords_exclude"
    const val KEY_SMSCODE_KEYWORDS_BLACKLIST = "pref_smscode_keywords_blacklist"
    const val KEY_SMSCODE_KEYWORDS_WHITELIST = "pref_smscode_keywords_whitelist"
    const val KEY_SMSCODE_REGEX = "pref_smscode_regex"
    const val KEY_SMSCODE_REGEX_EXCLUDE = "pref_smscode_regex_exclude"
    const val KEY_RELAY_KEYWORDS = "pref_relay_keywords"
    const val KEY_RELAY_KEYWORDS_CASE_INSENSITIVE = "pref_relay_keywords_case_insensitive"
    const val KEY_RELAY_KEYWORDS_REGEX = "pref_relay_keywords_regex"
    const val KEY_RELAY_TEST = "pref_relay_test"
    const val KEY_CODE_RULES = "pref_code_rules"

    // Experimental
    const val KEY_MARK_AS_READ = "pref_mark_as_read"
    const val KEY_DELETE_SMS = "pref_delete_sms"
    const val KEY_FORCE_STOP_RECOVERY = "pref_force_stop_recovery"
    const val KEY_FORCE_STOP_RECOVERY_RELAUNCH_ONCE = "pref_force_stop_recovery_relaunch_once"

    // Keep-alive hooks
    const val KEY_KEEPALIVE_OOM_ADJ = "pref_keepalive_oom_adj"
    const val KEY_KEEPALIVE_ANTI_KILL = "pref_keepalive_anti_kill"
    const val KEY_KEEPALIVE_STANDBY_BYPASS = "pref_keepalive_standby_bypass"
    const val KEY_KEEPALIVE_DOZE_BYPASS = "pref_keepalive_doze_bypass"
    const val KEY_KEEPALIVE_ACCESSIBILITY_HEARTBEAT = "pref_keepalive_accessibility_heartbeat"
    const val KEY_KEEPALIVE_DEDICATED_SERVICE = "pref_keepalive_dedicated_service"

    // Others
    const val KEY_VERBOSE_LOG_MODE = "pref_verbose_log_mode"
    const val KEY_SENSITIVE_DEBUG_LOG_MODE = "pref_sensitive_debug_log_mode"
    const val KEY_RUNTIME_LOG_RETENTION_DAYS = "pref_runtime_log_retention_days"
    const val RUNTIME_LOG_RETENTION_DAYS_DEFAULT = 7
    const val RUNTIME_LOG_RETENTION_DAYS_MIN = 1
    @Deprecated("Runtime logs now rotate by day; use KEY_RUNTIME_LOG_RETENTION_DAYS.")
    const val KEY_RUNTIME_LOG_FILE_SIZE_MB = "pref_runtime_log_file_size_mb"
    @Deprecated("Runtime logs now rotate by day; use RUNTIME_LOG_RETENTION_DAYS_DEFAULT.")
    const val RUNTIME_LOG_FILE_SIZE_MB_DEFAULT = 1
    @Deprecated("Runtime logs now rotate by day; use RUNTIME_LOG_RETENTION_DAYS_MIN.")
    const val RUNTIME_LOG_FILE_SIZE_MB_MIN = 1
    const val KEY_ENABLE_ANALYTICS = "pref_enable_analytics"
    const val KEY_HOME_CARD_ORDER = "pref_home_card_order"
    const val KEY_HOME_CARD_ENABLED = "pref_home_card_enabled"
    const val KEY_HOME_CHART_TYPE = "pref_home_chart_type"
    const val KEY_HOME_CHART_WINDOW = "pref_home_chart_window"
    const val KEY_AUTO_UPDATE_ON_START = "pref_auto_update_on_start"
    const val KEY_AUTO_UPDATE_WIFI_ONLY = "pref_auto_update_wifi_only"
    const val KEY_GITHUB_IGNORED_VERSION = "pref_github_ignored_version"
    const val KEY_LOW_BATTERY_REMINDER_ENABLE = "pref_low_battery_reminder_enable"
    const val KEY_LOW_BATTERY_THRESHOLD = "pref_low_battery_threshold"
    const val LOW_BATTERY_THRESHOLD_DEFAULT = 20
    const val KEY_LOW_BATTERY_CHANNEL_ID = "pref_low_battery_channel_id"
    const val KEY_INTERNAL_LOW_BATTERY_BELOW = "internal_low_battery_below"
    const val KEY_FULL_BATTERY_REMINDER_ENABLE = "pref_full_battery_reminder_enable"
    const val KEY_FULL_BATTERY_CHANNEL_ID = "pref_full_battery_channel_id"
    const val KEY_INTERNAL_FULL_BATTERY_ABOVE = "internal_full_battery_above"
    const val KEY_CHARGING_CHANGE_REMINDER_ENABLE = "pref_charging_change_reminder_enable"
    const val KEY_CHARGING_CHANGE_CHANNEL_ID = "pref_charging_change_channel_id"
    const val KEY_INTERNAL_CHARGING_STATE = "internal_charging_state"
    const val KEY_CALL_ALERT_LOCAL_ENABLED = "pref_call_alert_local_enabled"
    const val KEY_CALL_ALERT_FORWARD_ENABLED = "pref_call_alert_forward_enabled"
    const val KEY_CALL_ALERT_CHANNEL_ID = "pref_call_alert_channel_id"
    const val KEY_VERIFICATION_FEATURES_ENABLED = "pref_verification_features_enabled"
    const val KEY_RELAY_FEATURES_ENABLED = "pref_relay_features_enabled"
    const val KEY_ENABLE_CALL_RELAY = "pref_enable_call_relay"
    const val KEY_ENABLE_SMS_RELAY = "pref_enable_sms_relay"
    const val KEY_ENABLE_APP_RELAY = "pref_enable_app_relay"
    const val KEY_RELAY_BY_WIFI = "pref_relay_by_wifi"
    const val KEY_RELAY_BY_DATA = "pref_relay_by_data"
    const val KEY_SMS_FORWARD_DEDUP_WINDOW_SEC = "pref_sms_forward_dedup_window_sec"
    const val SMS_FORWARD_DEDUP_WINDOW_SEC_DEFAULT = 60
    const val SMS_FORWARD_DEDUP_WINDOW_SEC_MIN = 10
    const val SMS_FORWARD_DEDUP_WINDOW_SEC_MAX = 300
    const val KEY_MSG_TYPE_SMS_CODE_ENABLED = "pref_msg_type_sms_code_enabled"
    const val KEY_MSG_TYPE_SMS_PLAIN_ENABLED = "pref_msg_type_sms_plain_enabled"
    const val KEY_MSG_TYPE_APP_NOTIFY_ENABLED = "pref_msg_type_app_notify_enabled"
    const val KEY_MSG_TYPE_CALL_NOTIFY_ENABLED = "pref_msg_type_call_notify_enabled"
    const val KEY_FORWARD_SMS_CODE_ENABLED = "pref_forward_sms_code_enabled"
    const val KEY_FORWARD_SMS_PLAIN_ENABLED = "pref_forward_sms_plain_enabled"
    const val KEY_FORWARD_APP_NOTIFY_ENABLED = "pref_forward_app_notify_enabled"
    const val KEY_FORWARD_CALL_NOTIFY_ENABLED = "pref_forward_call_notify_enabled"
    const val KEY_FORWARD_CALL_NOTIFY_FINAL_ENABLED = "pref_forward_call_notify_final_enabled"
    const val KEY_SMS_KEYWORD_ALERT_ENABLED = "pref_sms_keyword_alert_enabled"
    const val KEY_SMS_KEYWORD_ALERT_KEYWORDS = "pref_sms_keyword_alert_keywords"
    const val KEY_SMS_KEYWORD_ALERT_NOTIFICATION = "pref_sms_keyword_alert_notification"
    const val KEY_SMS_KEYWORD_ALERT_SOUND = "pref_sms_keyword_alert_sound"
    const val KEY_SMS_KEYWORD_ALERT_VIBRATE = "pref_sms_keyword_alert_vibrate"
    const val KEY_APP_KEYWORD_ALERT_ENABLED = "pref_app_keyword_alert_enabled"
    const val KEY_APP_KEYWORD_ALERT_KEYWORDS = "pref_app_keyword_alert_keywords"
    const val KEY_APP_KEYWORD_ALERT_NOTIFICATION = "pref_app_keyword_alert_notification"
    const val KEY_APP_KEYWORD_ALERT_SOUND = "pref_app_keyword_alert_sound"
    const val KEY_APP_KEYWORD_ALERT_VIBRATE = "pref_app_keyword_alert_vibrate"

    // About
    const val KEY_ABOUT = "pref_about"
    const val KEY_VERSION = "pref_version"
    const val KEY_JOIN_QQ_GROUP = "pref_join_qq_group"
    const val KEY_SOURCE_CODE = "pref_source_code"
    const val KEY_DONATE_BY_ALIPAY = "pref_donate_by_alipay"
    const val KEY_PRIVACY_POLICY = "pref_privacy_policy"
    const val KEY_PRIVACY_POLICY_ACCEPTED = "pref_privacy_policy_accepted"
    const val KEY_BACKUP_COMPAT_TIP_SHOWN = "pref_backup_compat_tip_shown"
    const val KEY_ENABLE_SMS_BLOCK = "enable_sms_block"
    const val KEY_ENABLE_NOTIFICATION_FORWARD = "enable_notification_forward"
    const val KEY_ABOUT_COMPOSE = "pref_about_compose"
    const val KEY_IPC_TOKEN = "ipc_token"
    const val KEY_FORWARD_COMMON_DEVICE_NAME = "pref_forward_common_device_name"
    const val KEY_FORWARD_COMMON_TEMPLATE = "pref_forward_common_template"
    const val KEY_FORWARD_APP_NOTIFY_TEMPLATE = "pref_forward_app_notify_template"
    const val KEY_FORWARD_CALL_NOTIFY_TEMPLATE = "pref_forward_call_notify_template"
    const val KEY_FORWARD_COMMON_INCLUDE_TIME = "pref_forward_common_include_time"
    const val KEY_FORWARD_COMMON_INCLUDE_SENDER = "pref_forward_common_include_sender"
    const val KEY_FORWARD_COMMON_INCLUDE_DEVICE_NAME = "pref_forward_common_include_device_name"
    const val KEY_FORWARD_COMMON_DISPATCH_STRATEGY = "pref_forward_common_dispatch_strategy"
    const val KEY_SIM_SLOT1_REMARK = "pref_sim_slot1_remark"
    const val KEY_SIM_SLOT2_REMARK = "pref_sim_slot2_remark"
    const val KEY_REMOTE_AGENT_BASE_URL = "pref_remote_agent_base_url"
    const val KEY_REMOTE_AGENT_USER_ID = "pref_remote_agent_user_id"
    const val KEY_REMOTE_AGENT_DEVICE_ID = "pref_remote_agent_device_id"
    const val KEY_REMOTE_AGENT_LAST_REVISION = "pref_remote_agent_last_revision"
    const val KEY_REMOTE_AGENT_SYNC_STATE = "pref_remote_agent_sync_state"
    const val KEY_REMOTE_AGENT_LAST_ERROR = "pref_remote_agent_last_error"
    const val KEY_REMOTE_AGENT_LAST_HEARTBEAT_AT = "pref_remote_agent_last_heartbeat_at"
    const val KEY_REMOTE_AGENT_LAST_PULL_AT = "pref_remote_agent_last_pull_at"
    const val KEY_REMOTE_AGENT_LAST_PUSH_AT = "pref_remote_agent_last_push_at"
    const val KEY_REMOTE_AGENT_PENDING_MUTATIONS = "pref_remote_agent_pending_mutations"
    const val KEY_REMOTE_AGENT_DEVICE_TOKEN = "pref_remote_agent_device_token"
    const val KEY_REMOTE_AGENT_LAST_APP_CATALOG_DIGEST = "pref_remote_agent_last_app_catalog_digest"
    private const val ACTION_NAMESPACE = "io.github.magisk317.relay"
    const val ACTION_FORWARD_SMS = "$ACTION_NAMESPACE.ACTION_FORWARD_SMS"
    const val ACTION_INGEST_CUSTOM_MESSAGE = "$ACTION_NAMESPACE.ACTION_INGEST_CUSTOM_MESSAGE"
    const val ACTION_LOW_BATTERY_REMINDER = "$ACTION_NAMESPACE.ACTION_LOW_BATTERY_REMINDER"
    const val ACTION_CALL_ALERT_LOCAL = "$ACTION_NAMESPACE.ACTION_CALL_ALERT_LOCAL"
    const val ACTION_CALL_ALERT_MONITOR_REFRESH = "$ACTION_NAMESPACE.ACTION_CALL_ALERT_MONITOR_REFRESH"
}
