#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "frontend/shared/contracts/openapi.json"
OUTPUT = ROOT / "frontend/shared/contracts/console.generated.ts"

HEADER = """// Generated from frontend/shared/contracts/openapi.json by
// scripts/codegen/generate_console_contract_from_openapi.py.
// Do not edit this file by hand.

"""


def load_schemas() -> dict[str, object]:
    document = json.loads(OPENAPI.read_text(encoding="utf-8"))
    schemas = document.get("components", {}).get("schemas")
    if not isinstance(schemas, dict):
        raise SystemExit(f"components.schemas missing in {OPENAPI}")
    return schemas


def ref_name(ref: str) -> str:
    return ref.rsplit("/", maxsplit=1)[-1]


def format_string_literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def is_valid_identifier(name: str) -> bool:
    return name.isidentifier() and not name[0].isdigit()


def render_property_name(name: str) -> str:
    return name if is_valid_identifier(name) else format_string_literal(name)


def render_type(schema: object) -> str:
    if schema is True:
        return "unknown"
    if not isinstance(schema, dict):
        return "unknown"

    if "$ref" in schema:
        return ref_name(str(schema["$ref"]))

    for union_key in ("anyOf", "oneOf"):
        variants = schema.get(union_key)
        if isinstance(variants, list) and variants:
            rendered_variants: list[str] = []
            for variant_schema in variants:
                rendered = render_type(variant_schema)
                if rendered not in rendered_variants:
                    rendered_variants.append(rendered)
            return " | ".join(rendered_variants) if rendered_variants else "unknown"

    enum_values = schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return " | ".join(format_string_literal(value) for value in enum_values)

    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        variants: list[str] = []
        for item_type in raw_type:
            if item_type == "null":
                variants.append("null")
            else:
                variants.append(render_type({**schema, "type": item_type}))
        deduped: list[str] = []
        for variant in variants:
            if variant not in deduped:
                deduped.append(variant)
        return " | ".join(deduped) if deduped else "unknown"

    if raw_type == "null":
        return "null"
    if raw_type == "string":
        return "string"
    if raw_type in {"integer", "number"}:
        return "number"
    if raw_type == "boolean":
        return "boolean"
    if raw_type == "array":
        return f"Array<{render_type(schema.get('items', True))}>"
    if raw_type == "object":
        properties = schema.get("properties")
        additional = schema.get("additionalProperties")
        if isinstance(properties, dict) and properties:
            rendered = ", ".join(
                f"{render_property_name(name)}: {render_type(prop_schema)}"
                for name, prop_schema in properties.items()
            )
            if additional is True:
                return f"{{ {rendered}; [key: string]: unknown }}"
            if isinstance(additional, dict):
                return f"{{ {rendered}; [key: string]: {render_type(additional)} }}"
            return f"{{ {rendered} }}"
        if additional is True:
            return "Record<string, unknown>"
        if isinstance(additional, dict):
            return f"Record<string, {render_type(additional)}>"
        return "Record<string, unknown>"

    return "unknown"


def render_schema(name: str, schema: object) -> str:
    if schema is True:
        return f"export type {name} = unknown\n"
    if not isinstance(schema, dict):
        return f"export type {name} = unknown\n"

    raw_type = schema.get("type")
    properties = schema.get("properties")
    additional = schema.get("additionalProperties")

    if raw_type == "object" and (not isinstance(properties, dict) or not properties):
        return f"export type {name} = {render_type(schema)}\n"

    if raw_type == "object" and isinstance(properties, dict):
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for prop_name, prop_schema in properties.items():
            optional = "" if prop_name in required else "?"
            lines.append(
                f"  {render_property_name(prop_name)}{optional}: {render_type(prop_schema)}"
            )
        if additional is True:
            lines.append("  [key: string]: unknown")
        elif isinstance(additional, dict):
            lines.append(f"  [key: string]: {render_type(additional)}")
        lines.append("}")
        return "\n".join(lines) + "\n"

    return f"export type {name} = {render_type(schema)}\n"


def generate_contract() -> str:
    schemas = load_schemas()
    blocks = [HEADER.rstrip()]
    for name in sorted(schemas):
        blocks.append(render_schema(name, schemas[name]).rstrip())
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if frontend/shared/contracts/console.generated.ts is not up to date",
    )
    args = parser.parse_args()

    rendered = generate_contract()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit(
                "console.generated.ts is out of date; run "
                "scripts/codegen/generate_console_contract_from_openapi.py"
            )
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
