#!/usr/bin/env python3
"""Generate shared config-root TypeScript types from Kotlin data classes."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCES = [
    ROOT / "modules/relay/contract/src/main/java/io/github/magisk317/relay/contract/model/LocalConfigMirrorPayload.kt",
    ROOT / "modules/relay/contract/src/main/java/io/github/magisk317/relay/contract/model/SenderActiveSchedule.kt",
    ROOT / "modules/relay/contract/src/main/java/io/github/magisk317/relay/contract/model/ForwardCommonConfig.kt",
    ROOT / "modules/relay/contract/src/main/java/io/github/magisk317/relay/contract/settings/SettingsModels.kt",
]
OUTPUT = ROOT / "frontend/shared/contracts/configRoot.generated.ts"

TYPE_ALIASES = {
    "LocalConfigMirrorPayload": "RemoteConfigRoot",
    "OverviewSettingsSnapshot": "SnapshotOverviewSettings",
}

PRIMITIVE_TYPES = {
    "String": "string",
    "Boolean": "boolean",
    "Int": "number",
    "Long": "number",
    "Float": "number",
    "Double": "number",
    "Date": "number",
}

SPECIAL_TYPES = {
    "JsonObject": "Record<string, unknown>",
    "SenderActiveSchedule": "SenderActiveSchedule",
}

REQUIRED_FIELD_OVERRIDES: dict[str, set[str]] = {
    "SnapshotSender": {
        "id",
        "type",
        "name",
        "jsonSetting",
        "status",
        "receiveCode",
        "receiveNonCode",
        "receiveAppNotify",
        "receiveCallNotify",
    },
    "SnapshotRule": {
        "id",
        "type",
        "filed",
        "check",
        "value",
        "senderId",
        "title",
        "status",
    },
    "SnapshotAppInfo": {
        "packageName",
        "blocked",
        "forwarding",
        "forwardingConfigured",
        "notifyTemplate",
    },
    "SnapshotSmsCodeRule": {
        "id",
        "codeKeyword",
        "codeRegex",
    },
    "SnapshotNotifyRouteRule": {
        "id",
        "scope",
        "packageName",
        "senderId",
        "updateTime",
    },
    "SnapshotForwardFilterRule": {
        "id",
        "msgType",
        "scopeType",
        "scopeKey",
        "senderId",
        "policy",
        "matchMode",
        "pattern",
        "enabled",
        "updateTime",
    },
    "SnapshotOverviewSettings": {
        "cardOrder",
        "enabledCardIds",
        "chartType",
        "chartWindow",
    },
}

HEADER = """// Generated from Kotlin config models by
// scripts/codegen/generate_config_root_contract.py.
// Do not edit this file by hand.

import type { SenderActiveSchedule } from '../senderActiveSchedule'

"""


@dataclass
class KotlinField:
    name: str
    type_name: str
    has_default: bool


@dataclass
class KotlinClass:
    name: str
    fields: list[KotlinField]


def split_top_level(value: str, delimiter: str = ",") -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    depth_round = depth_angle = depth_square = depth_curly = 0
    in_string = False
    escape = False

    for char in value:
        current.append(char)
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue

        if char == '"':
            in_string = True
        elif char == "(":
            depth_round += 1
        elif char == ")":
            depth_round -= 1
        elif char == "<":
            depth_angle += 1
        elif char == ">":
            depth_angle -= 1
        elif char == "[":
            depth_square += 1
        elif char == "]":
            depth_square -= 1
        elif char == "{":
            depth_curly += 1
        elif char == "}":
            depth_curly -= 1
        elif (
            char == delimiter
            and depth_round == 0
            and depth_angle == 0
            and depth_square == 0
            and depth_curly == 0
        ):
            part = "".join(current[:-1]).strip()
            if part:
                parts.append(part)
            current = []

    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def strip_annotations(value: str) -> str:
    lines = []
    for line in value.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("@"):
            continue
        lines.append(stripped)
    return " ".join(lines)


def parse_field(raw_field: str) -> KotlinField | None:
    serial_name_match = re.search(r'@SerialName\("([^"]+)"\)', raw_field)
    normalized = strip_annotations(raw_field)
    normalized = normalized.replace("override ", "")
    match = re.search(r"\b(?:val|var)\s+(\w+)\s*:\s*([^=]+)", normalized)
    if not match:
        return None
    property_name = match.group(1)
    type_name = match.group(2).strip().rstrip(",")
    return KotlinField(
        name=serial_name_match.group(1) if serial_name_match else property_name,
        type_name=type_name,
        has_default="=" in normalized,
    )


def parse_kotlin_classes() -> dict[str, KotlinClass]:
    classes: dict[str, KotlinClass] = {}
    for path in SOURCES:
        source = path.read_text(encoding="utf-8")
        index = 0
        marker = "data class "
        while True:
            start = source.find(marker, index)
            if start < 0:
                break
            name_start = start + len(marker)
            name_match = re.match(r"(\w+)", source[name_start:])
            if not name_match:
                index = name_start
                continue
            class_name = name_match.group(1)
            after_name = source[name_start + len(class_name):]
            paren_offset = after_name.find("(")
            if paren_offset < 0:
                index = name_start + len(class_name)
                continue
            body_start = name_start + len(class_name) + paren_offset + 1
            depth = 1
            position = body_start
            while position < len(source) and depth:
                char = source[position]
                if char == "(":
                    depth += 1
                elif char == ")":
                    depth -= 1
                position += 1
            body = source[body_start : position - 1]
            fields = [field for part in split_top_level(body) if (field := parse_field(part))]
            classes[class_name] = KotlinClass(name=class_name, fields=fields)
            index = position
    return classes


def map_type(type_name: str) -> str:
    nullable = type_name.endswith("?")
    base = type_name[:-1].strip() if nullable else type_name.strip()

    if base in PRIMITIVE_TYPES:
        mapped = PRIMITIVE_TYPES[base]
    elif base in SPECIAL_TYPES:
        mapped = SPECIAL_TYPES[base]
    elif base.startswith("List<") and base.endswith(">"):
        inner = base[5:-1].strip()
        mapped = f"Array<{map_type(inner)}>"
    elif base.startswith("Map<") and base.endswith(">"):
        key_value = split_top_level(base[4:-1])
        if len(key_value) == 2:
            _, value_type = key_value
            mapped = f"Record<string, {map_type(value_type)}>"
        else:
            mapped = "Record<string, unknown>"
    else:
        mapped = TYPE_ALIASES.get(base, base)

    if nullable:
        return f"{mapped} | null"
    return mapped


def emit_interface(kotlin_class: KotlinClass) -> str:
    output_name = TYPE_ALIASES.get(kotlin_class.name, kotlin_class.name)
    extends_clause = " extends Record<string, unknown>" if output_name == "RemoteConfigRoot" else ""
    required_fields = REQUIRED_FIELD_OVERRIDES.get(output_name, set())
    lines = [f"export interface {output_name}{extends_clause} {{"]
    for field in kotlin_class.fields:
        optional = "" if field.name in required_fields or not field.has_default else "?"
        lines.append(f"  {field.name}{optional}: {map_type(field.type_name)}")
    lines.append("}")
    return "\n".join(lines)


def collect_reachable_types(classes: dict[str, KotlinClass], root_name: str) -> list[str]:
    reachable: list[str] = []
    seen: set[str] = set()

    def visit(type_name: str) -> None:
        nullable = type_name.endswith("?")
        base = type_name[:-1].strip() if nullable else type_name.strip()
        if base.startswith("List<") and base.endswith(">"):
            visit(base[5:-1].strip())
            return
        if base.startswith("Map<") and base.endswith(">"):
            parts = split_top_level(base[4:-1])
            if len(parts) == 2:
                visit(parts[1].strip())
            return
        if base in PRIMITIVE_TYPES or base in SPECIAL_TYPES:
            return
        if base not in classes or base in seen:
            return
        seen.add(base)
        for field in classes[base].fields:
            visit(field.type_name)
        reachable.append(base)

    visit(root_name)
    return list(reversed(reachable))


def generate_contract() -> str:
    classes = parse_kotlin_classes()
    order = collect_reachable_types(classes, "LocalConfigMirrorPayload")
    blocks = [HEADER.rstrip()]
    for class_name in order:
        blocks.append(emit_interface(classes[class_name]).rstrip())
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if frontend/shared/contracts/configRoot.generated.ts is not up to date",
    )
    args = parser.parse_args()

    rendered = generate_contract()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
